config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :user, controllers: {  
    # confirmations: 'users/confirmations',
    passwords: 'devise/passwords',
    registrations: 'users/registrations',
    sessions: 'devise/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
    # unlocks: 'users/unlocks',
  }, skip: [:sessions]

  ## custom routes for users
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'register' => 'devise/registrations#new'
  end

  resources :posts, only: [:create, :destroy] do
    resources :comments, only: :create
    resources :likes,    only: :create
  end

  resources :photos, only: [:create, :destroy] do
    resources :comments, only: :create
    resources :likes,    only: :create
    post 'set_profile', to: 'users#set_profile_photo'
  end

  resources :comments, only: :destroy
  resources :likes,    only: :destroy

  resources :users, only: [:show] do
    resources :photos,   only: :index
    resources :requests, only: :create
    resources :friends,  only: :index, controller: 'friendships'
  end

  resources :requests, only: :update

  resources :friendships, only: :destroy
  get '/find_friends', to: 'friendships#find_new'
end

app/controllers/static_pages_controller.rb
require 'will_paginate/array'

class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:home]

  def home
    @user = current_user

    @feed_items = current_user.feed.paginate(page: params[:page], per_page: 20)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.slim
= provide(:title, 'Welcome')
section.section
  .container
    .columns
      .column.is-3.is-offset-1
        = render partial: 'users/stats', locals: { user: @user }
        .box
          h1.subtitle Friend Requests:
          = link_to "Find new friends", find_friends_path, class: 'button is-success'
          br: br
          - if current_user.received_requests.any?
            - current_user.received_requests.each do |request|
              article.media
                .figure.media-left
                  p.image.is-32x32
                    = image_tag request.user.profile_photo_path
                .media-content
                  = link_to request.user.name, request.user
                .media-right
                  = button_to(request_path(request), method: :put, class: 'button is-success is-small') do |b|
                    span.icon.is-small
                      i.fa.fa-user-plus
                    span Accept
          - else
            span: em You have no requests.
      .column.is-7
        h1.title News Feed
        .box
          .tabs.is-boxed.is-small
            ul
              li.is-active data-tab="tab-1"
                a
                  span.icon.is-small: i.fa.fa-file-text-o
                  span Status Update
              li data-tab="tab-2"
                a
                  span.icon.is-small: i.fa.fa-picture-o
                  span Post Photo
          #tab-1.tab-content.current
            article.media
              .figure.media-left
                p.image.is-64x64
                  = image_tag(current_user.profile_photo_path)
              .media-content
                = form_for(current_user.posts.build, remote: true) do |f|
                  p.control
                    = f.text_area :body, class: 'textarea', placeholder: "What's on your mind?",
                                                            autofocus: true, required: true
                  nav.level
                    .level-left
                    .level-right
                      .level-item
                        = f.submit "Post", class: 'button is-info'
          #tab-2.tab-content
            article.media
              .figure.media-left
                p.image.is-64x64
                  = image_tag(current_user.profile_photo_path)
              .media-content
                = form_for(current_user.photos.build, remote: true, html: { multipart: true }) do |f|
                  = hidden_field_tag :authenticity_token, form_authenticity_token
                  = f.label :file
                  p.control
                    = f.file_field :file, required: true
                  = f.label :description
                  p.control
                    = f.text_field :description, class: 'input', required: true
                  nav.level
                    .level-left
                    .level-right
                      .level-item
                        = f.submit "Post", class: 'button is-info'
        .box#feed
          - @feed_items.each do |feed_item|
            - if feed_item.persisted?
              = render feed_item
        .pagination
            = will_paginate @feed_items, page_links: false