config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :user, controllers: {  
    # confirmations: 'users/confirmations',
    passwords: 'devise/passwords',
    registrations: 'users/registrations',
    sessions: 'devise/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
    # unlocks: 'users/unlocks',
  }, skip: [:sessions]

  ## custom routes for users
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'register' => 'devise/registrations#new'
  end

  resources :posts, only: [:create, :destroy] do
    resources :comments, only: :create
    resources :likes,    only: :create
  end

  resources :photos, only: [:create, :destroy] do
    resources :comments, only: :create
    resources :likes,    only: :create
    post 'set_profile', to: 'users#set_profile_photo'
  end

  resources :comments, only: :destroy
  resources :likes,    only: :destroy

  resources :users, only: [:show] do
    resources :photos,   only: :index
    resources :requests, only: :create
    resources :friends,  only: :index, controller: 'friendships'
  end

  resources :requests, only: :update

  resources :friendships, only: :destroy
  get '/find_friends', to: 'friendships#find_new'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  validates :user, :likeable, { presence: true }

  validates_uniqueness_of :user_id, scope: [:likeable_id, :likeable_type]
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :destroy

  def create
    # @post = Post.find(params[:post_id])
    @likeable = get_likeable

    @like = @likeable.likes.build
    @like.user_id = current_user.id
    if @like.save
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_url) }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_url) }
      end
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @likeable = @like.likeable
    @like.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end

  private
    def correct_user
      @like = current_user.likes.find_by(id: params[:id])
      redirect_to root_url if @like.nil?
    end

    def get_likeable
      params.each do |name, value|
        if name =~ /(.+)_id$/
          return $1.classify.constantize.find(value)
        end
      end
      nil
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_button.html.slim
- like = object.likes.find_by(user: current_user)
- unless like.nil?
  = button_to(like_path(like), method: :delete, remote: true, class: 'button is-small is-info is-pulled-left') do |b|
    span.icon.is-small: i.fa.fa-thumbs-o-up
    span Liked
- else
  = button_to(polymorphic_path([object, Like.new]), remote: true, class: 'button is-small is-link is-pulled-left') do |b|
    span.icon.is-small: i.fa.fa-thumbs-o-up
    span Like
small &nbsp;(#{pluralize object.likes.count, 'like'})&nbsp;

app/views/likes/create.js.erb
var $likeable = ".<%= @likeable.class.to_s.downcase %>-<%= @likeable.id %>";
var $likeButton  = "<%= escape_javascript render(partial: 'likes/like_button', locals: { object: @likeable }) %>";

$($likeable).find('.like-button').hide().html($likeButton).fadeIn('fast');

app/views/likes/destroy.js.erb
var $likeable = ".<%= @likeable.class.to_s.downcase %>-<%= @likeable.id %>";
var $likeButton  = "<%= escape_javascript render(partial: 'likes/like_button', locals: { object: @likeable }) %>";

$($likeable).find('.like-button').hide().html($likeButton).fadeIn();