config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :user, controllers: {  
    # confirmations: 'users/confirmations',
    passwords: 'devise/passwords',
    registrations: 'users/registrations',
    sessions: 'devise/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
    # unlocks: 'users/unlocks',
  }, skip: [:sessions]

  ## custom routes for users
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'register' => 'devise/registrations#new'
  end

  resources :posts, only: [:create, :destroy] do
    resources :comments, only: :create
    resources :likes,    only: :create
  end

  resources :photos, only: [:create, :destroy] do
    resources :comments, only: :create
    resources :likes,    only: :create
    post 'set_profile', to: 'users#set_profile_photo'
  end

  resources :comments, only: :destroy
  resources :likes,    only: :destroy

  resources :users, only: [:show] do
    resources :photos,   only: :index
    resources :requests, only: :create
    resources :friends,  only: :index, controller: 'friendships'
  end

  resources :requests, only: :update

  resources :friendships, only: :destroy
  get '/find_friends', to: 'friendships#find_new'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :posts,  dependent: :destroy
  has_many :photos, dependent: :destroy

  belongs_to :profile_photo, class_name: 'Photo', foreign_key: 'profile_photo_id'

  has_many :requests, dependent: :destroy
  has_many :sent_requests,     class_name: 'Request', foreign_key: 'user_id', 
                               dependent: :destroy
  has_many :received_requests, class_name: 'Request', foreign_key: 'friend_id', 
                               dependent: :destroy
  
  has_many :friends_requested,  through: :sent_requests,     source: :friend
  has_many :friends_requesting, through: :received_requests, source: :user


  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :comments
  has_many :likes

  validates :name, presence: true, length: { maximum: 50 }

  def feed
    ids = self.friends.pluck(:id) << self.id
    posts    = Post.where(user_id: ids)
    photos   = Photo.where(user_id: ids)
    combined = ( posts + photos ).sort_by(&:created_at).reverse

    return combined
  end

  def personal_feed
    posts  = self.posts
    photos = self.photos
    combined = ( posts + photos ).sort_by(&:created_at).reverse

    return combined
  end

  def profile_photo_path
    if profile_photo.nil?
      'fallback/default.jpg'
    else
      profile_photo.file.url(:thumb)
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to cancel_user_registration_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  def create
    super
    if @user.persisted?
      UserMailer.welcome(@user).deliver_now
    end
  end

  # Overwrite update_resource to let users to update their user without giving their password
  def update_resource(resource, params)
    if current_user.provider == "facebook"
      params.delete("current_password")
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
    end
end

app/controllers/users_controller.rb
require 'will_paginate/array'

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :set_profile_photo

  def show
    @user = User.find(params[:id])
    @feed_items = @user.personal_feed.paginate(page: params[:page], per_page: 20)
  end

  def set_profile_photo
    photo = Photo.find(params[:photo_id])
    user  = current_user
    user.profile_photo = photo
    if user.save
      flash[:notice] = "Profile photo updated"
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def correct_user
      photo = current_user.photos.find_by(id: params[:photo_id])
      redirect_to root_url if photo.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_stats.html.slim
.box
  article.media
    .figure.media-left
      p.image.is-128x128
        = link_to user_photos_path(user) do
          = image_tag user.profile_photo_path
    .media-content
      h1.subtitle = link_to user.name, user
      - unless user == current_user
        div class="request-buttons-#{user.id}"
          = render partial: 'requests/request_button', locals: { user: user }
      - else
        span: em = link_to "Edit info", edit_user_registration_path
  br
  h3.subtitle Friends:
  - if user.friends.any?
    - user.friends.take(6).each do |friend|
      article.media
        .figure.media-left
          p.image.is-32x32
            = link_to friend do
              = image_tag friend.profile_photo_path
        .media-content
          = link_to friend.name, friend
    - if user.friends.count > 6
      em.is-pulled-right: = link_to "View all friends...", user_friends_path(user), class: 'button'
      br
  - else
    p: em This user has no friends.

app/views/users/show.html.slim
section.section
  .container
    .columns
      .column.is-3.is-offset-1
        = render partial: 'stats', locals: { user: @user }
      .column.is-7
        h1.title = "Timeline"
        .box#feed
          - if @feed_items.any?
            - @feed_items.each do |feed_item|
              = render feed_item
          - else
            .box
              article.media
                .media-content
                  p This user has no contributions to display.
        .pagination
          = will_paginate @feed_items, page_links: false