config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :user, controllers: {  
    # confirmations: 'users/confirmations',
    passwords: 'devise/passwords',
    registrations: 'users/registrations',
    sessions: 'devise/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
    # unlocks: 'users/unlocks',
  }, skip: [:sessions]

  ## custom routes for users
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'register' => 'devise/registrations#new'
  end

  resources :posts, only: [:create, :destroy] do
    resources :comments, only: :create
    resources :likes,    only: :create
  end

  resources :photos, only: [:create, :destroy] do
    resources :comments, only: :create
    resources :likes,    only: :create
    post 'set_profile', to: 'users#set_profile_photo'
  end

  resources :comments, only: :destroy
  resources :likes,    only: :destroy

  resources :users, only: [:show] do
    resources :photos,   only: :index
    resources :requests, only: :create
    resources :friends,  only: :index, controller: 'friendships'
  end

  resources :requests, only: :update

  resources :friendships, only: :destroy
  get '/find_friends', to: 'friendships#find_new'
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user,   presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }
  validate  :not_self
  validate  :not_friends
  validate  :not_pending

  def accept
    user.friends << friend
    destroy
  end

  private

    def not_self
      errors.add(:friend, "can't be equal to user") if user == friend
    end

    def not_friends
      errors.add(:friend, "is already added") if user.friends.include?(friend)
    end

    def not_pending
      errors.add(:friend, "already requested friendship") if friend.friends_requested.include?(user)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    @request = current_user.requests.new(friend: @user)

    if @request.save
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    @request = Request.find(params[:id])
    @request.accept
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_request_button.html.slim
- if current_user.friends_requested.include?(user)
  button.button.is-success.is-small.is-active
    span.icon.is-small
      i.fa.fa-check-circle
    span Request Sent
- elsif current_user.friends_requesting.include?(user)
  - request = current_user.received_requests.find_by(user_id: user.id)
  = button_to(request_path(request), method: :put, class: 'button is-success is-small') do |b|
    span.icon.is-small
      i.fa.fa-user-plus
    span Accept Request
- elsif current_user.friends.include?(user)
  - friendship = current_user.friendships.find_by(user_id: current_user.id, friend_id: user.id)
  button.button.is-success.is-small.is-active
    span.icon.is-small
      i.fa.fa-check-circle
    span Friends
  br
  small: em = link_to "(Unfriend)", friendship_path(friendship), method: :delete
- else
  = button_to(user_requests_path(user), remote: true, class: 'button is-success is-small is-active') do |b|
    span.icon.is-small
      i.fa.fa-user-plus
    span Add Friend

app/views/requests/create.js.erb
var $buttonsContainer = ".request-buttons-<%= @user.id %>"
var $buttons = "<%= escape_javascript render(partial: 'request_button', locals: { user: @user }) %>"

$($buttonsContainer).hide().html($buttons).fadeIn();